In [12]:
import numpy as np

# numpy array repersentation
np = np.array([1,2,3,4])
print(np)
print(type(np))

[1 2 3 4]
<class 'numpy.ndarray'>


In [13]:
#list repersentation
np = [1,2,3,4]
print(np)
print(type(np))

[1, 2, 3, 4]
<class 'list'>


In [14]:
# List is comma seprated and numpy is not 

In [15]:
import numpy as np
array = np.array([1,2,3,4])
print(array)
print(array.ndim)

# 2D data

array_2d = np.array([[1,2,3,4],[4,4,5,9]])
print(array_2d)
print(array_2d.ndim)

[1 2 3 4]
1
[[1 2 3 4]
 [4 4 5 9]]
2


# Special numpy array

# zeros


In [16]:
zero = np.zeros(4)
print(zero)

zero_dim = np.zeros((3,4), int)
print(zero_dim)

[0. 0. 0. 0.]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# ones


In [17]:
ones = np.ones((4,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# empty

In [18]:
emp_arr = np.empty(4)
print(emp_arr)

[0. 0. 0. 0.]


# arange

In [19]:
arrange_arr = np.arange(10)
print(arrange_arr)

[0 1 2 3 4 5 6 7 8 9]


# Daigonal eye function 

In [20]:
diagonal_arr = np.eye(4,3)
print(diagonal_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


# Create numpy Array With Random Number

# rand: The rand function is used to create random values between 0 to 1

In [21]:
import numpy as np 

var = np.random.rand(4)

print(var)

[0.82875732 0.91016529 0.64536567 0.79965393]


In [22]:
import numpy as np 

var = np.random.rand(4,3)

print(var)

[[0.01101983 0.48843764 0.51738637]
 [0.70751987 0.68649479 0.22908571]
 [0.45653491 0.27591748 0.77815227]
 [0.7690982  0.17800872 0.78865466]]


In [23]:
import numpy as np 

var = np.random.rand(4,3,2)

print(var)

[[[0.14147291 0.98315159]
  [0.08190232 0.74421983]
  [0.83208678 0.06611098]]

 [[0.14886237 0.8707187 ]
  [0.23309855 0.47112668]
  [0.76465541 0.7125558 ]]

 [[0.92780803 0.07169894]
  [0.9723991  0.71084389]
  [0.95123142 0.70805821]]

 [[0.08417309 0.43218454]
  [0.21382674 0.46985417]
  [0.8615761  0.83585313]]]


# randn(): This function is used to generate a random values close to zero . This may return possitive or negative values aswell

In [24]:
import numpy as np

var = np.random.randn(10)

print(var)

[-0.07615591 -0.57307806 -0.84566334  0.50561068  0.09369914 -0.59249923
 -0.12768228  1.07659122  0.19026131  0.14552104]


In [25]:
import numpy as np

var = np.random.randn(10,3)

print(var)

[[ 1.28480272 -0.2301809  -1.91221207]
 [-0.33728353 -0.15641203 -1.77067115]
 [ 0.03600938  1.53063457 -0.66110319]
 [-1.16859858  0.36816942 -0.57603642]
 [-1.67631886 -0.30007251  1.56062576]
 [-0.60980299  0.29231794 -0.42790487]
 [-0.20661943 -0.21561642  0.34349388]
 [-1.01624426  0.31938376 -0.56588861]
 [ 1.3583104  -0.80061958 -0.41923863]
 [ 1.86688005  0.07023488 -1.04746159]]


# ranf(): The function for random sampling in numpy . It return an array for specific shape and fill it with random floats in the half-open interval[0.0,1.0)

In [26]:
import numpy as np

arr_var = np.random.ranf(4)

print(arr_var)

[0.14351561 0.58376108 0.90543425 0.0732361 ]


# randint(): This function is used to create random number between given number

In [ ]:
import numpy as np

arr_var = np.random.randint(1,20,10)
print(arr_var)