# indexing

In [7]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[4])
print(arr[-5])
print(arr)

5
1
[1 2 3 4 5]


In [9]:
array_2d = np.array([[1,2,3,4],[2,3,4,5]])

print(array_2d)

print(array_2d[1,1])

[[1 2 3 4]
 [2 3 4 5]]
3


# slice

In [16]:
array = np.array([1,2,3,4,5,6,7,])

print(array[1:])

print(array[1:6:2])# jumpy by one value 

[2 3 4 5 6 7]
[2 4 6]


In [18]:
array = np.array([[1,2,3,4,5],[12,34,56,78,90],[98,80,43,21,54]])
print(array)

print(array[1,1:]) # frist index is for moving to the array (1: [12,34,56,78,90])

[[ 1  2  3  4  5]
 [12 34 56 78 90]
 [98 80 43 21 54]]
[34 56 78 90]
