# view vs copy

In [4]:
import numpy as np

arr = np.array([1,2,3,4,5])

new = arr.view()
arr[1] = 10
print(new)
print(arr)

[ 1 10  3  4  5]
[ 1 10  3  4  5]


In [5]:
import numpy as np

arr = np.array([1,2,3,4,5])

new = arr.copy()
arr[1] = 10
print(new)
print(arr)

[1 2 3 4 5]
[ 1 10  3  4  5]
